services:
  nginx:
    hostname: "nginx.local"
    build: "./containers/nginx"
    restart: always  # fix when mariadb hasn't started listening and backend crashes
    ports:
      - "443:443"  # HTTPS port forward
    depends_on:
      - "frontend"
  frontend:
    hostname: "frontend.local"
    image: mutate8694/frontend:latest
    depends_on:
      - "backend"
    environment:
      - NEXT_PUBLIC_BACKEND_BASE_URL=http://localhost:1234
  backend:
    hostname: "backend.local"
    image: mutate8694/backend:latest
    restart: always  # fix when mariadb hasn't started listening and backend crashes
    depends_on:
      - "mariadb"
    environment:
      - DB_URL=mysql+pymysql://root:admin@mariadb.local:3306/Zorgdb
  mariadb:
    hostname: "mariadb.local"
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
