services:
  nginx:
    hostname: "nginx.local"
    build: "./containers/nginx"
    restart: always  # fix when mariadb hasn't started listening and backend crashes
    ports:
      - "80:80"  # HTTP port forward
      - "443:443"  # HTTPS port forward
    depends_on:
      - "frontend"
  frontend:
    hostname: "frontend.local"
    build: https://github.com/ZuydUniversity/B2C6_B2D_Frontend.git#groep-2
    depends_on:
      - "backend"
  backend:
    hostname: "backend.local"
    build: https://github.com/ZuydUniversity/B2C6_B2D_Backend.git#Groep-2
    restart: always  # fix when mariadb hasn't started listening and backend crashes
    depends_on:
      - "mariadb"
    environment:
      - DB_URL=mysql+pymysql://root:admin@mariadb.local:3306/Zorgdb
  mariadb:
    hostname: "mariadb.local"
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
