# inspired by https://learn.microsoft.com/en-us/azure/developer/ansible/vm-configure?tabs=ansible

# install deps: `ansible-galaxy collection install azure.azcollection`
# https://learn.microsoft.com/en-us/azure/developer/ansible/install-on-linux-vm?tabs=azure-cli#install-ansible-on-an-azure-linux-virtual-machine

- name: Create Azure VM
  hosts: localhost
  connection: local
  vars_files:
    - ./vars/azure.yml
    - ./vars/vm.yml
  tasks:
    # hbo casus heeft geen permissions voor resource group create: hergebruik "{{ resgroup_name }}"
    # - name: Create resource group
    #  azure_rm_resourcegroup:
    #    name: "{{ resgroup_name }}"
    #    location: eastus

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resgroup_name }}"
        name: groep2-vnet
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet to vnet
      azure_rm_subnet:
        resource_group: "{{ resgroup_name }}"
        name: groep2-vnet-subnet
        address_prefix: "10.0.1.0/24"
        virtual_network: groep2-vnet

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resgroup_name }}"
        allocation_method: Static
        name: groep2-vm-ip-1
      register: output_ip_address

    - name: Create Network Security Group that allows SSH and HTTP
      azure_rm_securitygroup:
        resource_group: "{{ resgroup_name }}"
        name: groep2-netsecgroup
        rules:  # rules cannot have same prio
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: HTTP
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1002
            direction: Inbound
          - name: HTTPS
            protocol: Tcp
            destination_port_range: 443
            access: Allow
            priority: 1003
            direction: Inbound

    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{ resgroup_name }}"
        name: groep2-vm-vnic-1
        virtual_network: groep2-vnet
        subnet: groep2-vnet-subnet
        security_group: groep2-netsecgroup
        # public_ip_name: groep2-vm-ip
        ip_configurations:
          - name: groep2-vm-ipconf
            public_ip_address_name: groep2-vm-ip-1

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resgroup_name }}"
        name: groep2-vm-1
        vm_size: Standard_B1s
        admin_username: "{{ vm_user_name }}"
        admin_password: "{{ vm_user_password }}"
        ssh_password_enabled: true
        network_interfaces: groep2-vm-vnic-1
        image:
          publisher: Debian
          offer: debian-12
          sku: 12  # select Debian-12 latest
          version: latest
        managed_disk_type: Standard_LRS  # locally redundant storage

    - name: Print IP
      ansible.builtin.debug:
        msg: "vm public ip: {{ output_ip_address.state.ip_address }}"
