# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "groep_3_B2D" ]
  pull_request:
    branches: ["groep_3_B2D"]




  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          pip install ansible
          ansible-galaxy collection install azure.azcollection --force

      - name: Install Azure Collection requirements
        run: pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt

      - name: Azure Login
        run: az login --service-principal --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.TENANT_ID }}

      - name: Create VMs
        run: |
          mkdir -p ~/.ssh
          cd Playbook/
          ansible-playbook create_vm.yml
        env:
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}


        #- name: Configure_VMs
         # run: |
          #cd Playbook/
          #ansible-Playbook configure_vms

