name: build_upload_docker

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DOCKERHUB_REPO_NAME:
        required: true

jobs:
  create_docker_image:
    runs-on: ubuntu-latest
    steps:
        - name: view codebase
          run: |
            echo "repo: ${{github.repository}}"
    
        - name: get codebase
          uses: actions/checkout@v3

        - name: Docker Login
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN}}
    
        - name: Build And Push
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO_NAME}}:latest
