name: run_docker_via_ssh

on:
  workflow_call:
    secrets:
      GROEP_2_DEPLOYMENT_VM_IP:
        required: true
      GROEP_2_DEPLOYMENT_VM_USER:
        required: true
      GROEP_2_DEPLOYMENT_VM_PASSWORD:
        required: true

jobs:
  run_docker_via_ssh:
    runs-on: ubuntu-latest
    steps:
        - name: create vm
          run: |
            git clone https://github.com/ZuydUniversity/B2C6_B2D_IAS --depth 1 --branch groep-2
            cd B2C6_B2D_IAS

            bash ./run_ansible_create_vm.sh
            

        - uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.GROEP_2_DEPLOYMENT_VM_IP }}
            username: ${{ secrets.GROEP_2_DEPLOYMENT_VM_USER }}
            password: ${{ secrets.GROEP_2_DEPLOYMENT_VM_PASSWORD }}
            script: |
              sudo apt update
              sudo apt install git -y

              git clone https://github.com/ZuydUniversity/B2C6_B2D_IAS --depth 1 --branch groep-2
              cd B2C6_B2D_IAS
              git pull  # pull updates if repo already exists (this vm is persistant)

              # run docker: rebuild images if there's updates and run em
              bash ./run_docker_compose.sh
            
              # stop ssh session (complete workflow step)
              exit
