name: deploy

on:
  workflow_call:
    secrets:
      GROEP_2_DEPLOYMENT_VM_IP:
        required: true
      GROEP_2_DEPLOYMENT_VM_USER:
        required: true
      GROEP_2_DEPLOYMENT_VM_PASSWORD:
        required: true
      GROEP_2_SLACK_WEBHOOK:
        required: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy_docker_via_ssh.yml
    secrets: inherit
  deploy-fail-notify:
    needs: deploy
    if: ${{ failure() }}
    uses: ./.github/workflows/send_slack_webhook.yml
    secrets: inherit
    with:
      SLACK_WEBHOOK_TEXT: ":rotating_light: [IAS] deploy: FAILED, commit info: <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|url>, workflow info: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|url> :rotating_light:"
  deploy-success-notify:
    needs: deploy
    if: ${{ success() }}
    uses: ./.github/workflows/send_slack_webhook.yml
    secrets: inherit
    with:
      SLACK_WEBHOOK_TEXT: ":white_check_mark: [IAS] deploy: SUCCEEDED, commit info: <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|url>, workflow info: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|url> :white_check_mark:"
    
