name: run_docker_via_ssh

on:
  workflow_call:
  
env:
  LOCAL_DIST: "/tmp/dist"
  REMOTE_HOST: "4.180.53.191"
  REMOTE_USER: "azureuser" 
  REMOTE_PASSWORD: "92ijetWDPi3yU4KkcUakuDmHZP6DLgps948KETSJuTmxNLurJxw7bRg4nMTtkqmqrW9VKubc"

jobs:
  run_docker_via_ssh:
    runs-on: ubuntu-latest
    steps:
        - name: create vm
          run: |
            git clone https://github.com/ZuydUniversity/B2C6_B2D_IAS --depth 1 --branch groep-2
            cd B2C6_B2D_IAS

            bash ./run_ansible_create_vm.sh
            

        - uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ env.REMOTE_HOST }}
            username: ${{ env.REMOTE_USER }}
            password: ${{ env.REMOTE_PASSWORD }}
            script: |
              sudo apt update
              sudo apt install git -y

              git clone https://github.com/ZuydUniversity/B2C6_B2D_IAS --depth 1 --branch groep-2
              cd B2C6_B2D_IAS
              git pull  # pull updates if repo already exists (this vm is persistant)

              # run docker: rebuild images if there's updates and run em
              bash ./run_docker_compose.sh
            
              # get ip
              echo "[+] hosting website on http://${{ env.REMOTE_HOST }}:8000"

              # stop ssh session (complete workflow step)
              exit

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.GROEP_2_SLACK_WEBHOOK }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK"
